server {
    listen 8443 ssl;
    server_name k8s-issuer-proxy;

    ssl_certificate /etc/nginx/certs/cert.pem;
    ssl_certificate_key /etc/nginx/certs/key.pem;

    location / {
        proxy_pass https://kafka-oauth-extension-control-plane:6443;
        proxy_ssl_certificate /etc/nginx/certs/apiserver-client-cert.pem;
        proxy_ssl_certificate_key /etc/nginx/certs/apiserver-client-key.pem;
        proxy_ssl_server_name on;
        proxy_ssl_verify off;
    }
}
